services:
  mtphotos:
    image: mtphotos/mt-photos:nodb-latest
    container_name: mtphotos
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "80:8063"
    volumes:
      - ./data/mtphotos/config:/config
      - ./data/mtphotos/upload:/upload
    environment:
      - MT_SERVER_PORT=8063
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - POSTGRES_HOST=mtphotos_db
      - POSTGRES_PASSWORD=mypassword
      - REDIS_HOST=mtphotos_cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=mypassword
    depends_on:
      mtphotos_db:
        condition: service_healthy
      mtphotos_cache:
        condition: service_healthy

  mtphotos_db:
    image: mtphotos/mt-photos-pg:latest # https://mtmt.tech/docs/advanced/ocr_api#vector
    container_name: mtphotos_pg
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  mtphotos_cache:
    image: redis:7-alpine
    container_name: mtphotos_redis
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--loglevel",
        "warning",
        "--requirepass",
        "mypassword"
      ]
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a mypassword ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    restart: on-failure

  mtphotos_ai:
    image: mtphotos/mt-photos-ai:onnx-latest
    container_name: mtphotos_ai
    restart: always
    environment:
      - API_AUTH_KEY=AB8C3768-0334-4B25-8FE5-3EF81C1158FD

  mtphotos_face_api:
    image: mtphotos/mt-photos-deepface:noavx-latest
    container_name: mtphotos_face_api
    restart: always
    environment:
      - API_AUTH_KEY=F809EB6F-5E36-44F7-924B-2D8E68D59297
